"""add qa_accounts token cache

Revision ID: 5829cd767b9d
Revises: f23e8c85aa71
Create Date: 2026-06-09 14:30:41.610324
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5829cd767b9d'
down_revision: Union[str, None] = 'f23e8c85aa71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_accounts', sa.Column('access_token', mysql.LONGTEXT(), nullable=True))
    op.add_column('qa_accounts', sa.Column('refresh_token', mysql.LONGTEXT(), nullable=True))
    op.add_column('qa_accounts', sa.Column('access_token_expired_at', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('qa_accounts', sa.Column('refresh_token_expired_at', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('qa_accounts', sa.Column('token_updated_at', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_accounts', 'token_updated_at')
    op.drop_column('qa_accounts', 'refresh_token_expired_at')
    op.drop_column('qa_accounts', 'access_token_expired_at')
    op.drop_column('qa_accounts', 'refresh_token')
    op.drop_column('qa_accounts', 'access_token')
    # ### end Alembic commands ###
