"""qa_runs.actors + qa_accounts.last_used_at

Revision ID: 88ca454eb9e0
Revises: 00048e91cda0
Create Date: 2026-06-08 11:19:52.032456
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '88ca454eb9e0'
down_revision: Union[str, None] = '00048e91cda0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_accounts', sa.Column('last_used_at', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('qa_runs', sa.Column('actors', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_runs', 'actors')
    op.drop_column('qa_accounts', 'last_used_at')
    # ### end Alembic commands ###
