"""add qa_markups resolved

Revision ID: 06c5835c0c2e
Revises: 3d90dca8bffb
Create Date: 2026-06-09 15:30:52.762625
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c5835c0c2e'
down_revision: Union[str, None] = '3d90dca8bffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_markups', sa.Column('resolved', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_markups', 'resolved')
    # ### end Alembic commands ###
