"""add qa_markups

Revision ID: f23e8c85aa71
Revises: 9ba25f019c6f
Create Date: 2026-06-09 11:41:24.178001
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f23e8c85aa71'
down_revision: Union[str, None] = '9ba25f019c6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_markups',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('route', sa.String(length=64), server_default='', nullable=False),
    sa.Column('selector', sa.Text(), nullable=True),
    sa.Column('element_text', sa.Text(), nullable=True),
    sa.Column('rect', mysql.JSON(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('screenshot_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('result', mysql.LONGTEXT(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_status_created', 'qa_markups', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_status_created', table_name='qa_markups')
    op.drop_table('qa_markups')
    # ### end Alembic commands ###
