"""init qa dashboard

Revision ID: d158a575cc0e
Revises: 
Create Date: 2026-06-04 15:55:23.915732
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd158a575cc0e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_cases',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('file', sa.String(length=255), server_default='', nullable=False),
    sa.Column('system', sa.String(length=16), server_default='', nullable=False),
    sa.Column('source', sa.String(length=16), server_default='builtin', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('step_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('yaml', mysql.LONGTEXT(), nullable=True),
    sa.Column('created_at', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_run_steps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=160), nullable=False),
    sa.Column('step_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('kind', sa.String(length=16), server_default='', nullable=False),
    sa.Column('name', sa.String(length=128), server_default='', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='', nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('observations', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_run', 'qa_run_steps', ['run_id', 'step_index'], unique=False)
    op.create_table('qa_runs',
    sa.Column('run_id', sa.String(length=160), nullable=False),
    sa.Column('case_id', sa.String(length=128), nullable=False),
    sa.Column('system', sa.String(length=16), server_default='', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('started_at', sa.Integer(), server_default='0', nullable=False),
    sa.Column('passed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_at', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=16), server_default='run', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('idx_case_started', 'qa_runs', ['case_id', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_case_started', table_name='qa_runs')
    op.drop_table('qa_runs')
    op.drop_index('idx_run', table_name='qa_run_steps')
    op.drop_table('qa_run_steps')
    op.drop_table('qa_cases')
    # ### end Alembic commands ###
