"""add qa_accounts pool

Revision ID: a612914a6fcd
Revises: 270c3415262b
Create Date: 2026-06-04 17:16:48.317774
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a612914a6fcd'
down_revision: Union[str, None] = '270c3415262b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('user_type', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=32), server_default='', nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('caps', mysql.JSON(), nullable=True),
    sa.Column('state', sa.String(length=16), server_default='available', nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('synced_at', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('lease_owner', sa.String(length=160), nullable=True),
    sa.Column('lease_expires_at', sa.BigInteger(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_role_state', 'qa_accounts', ['role', 'state'], unique=False)
    op.create_index('uq_account_role', 'qa_accounts', ['account_id', 'role'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_account_role', table_name='qa_accounts')
    op.drop_index('idx_role_state', table_name='qa_accounts')
    op.drop_table('qa_accounts')
    # ### end Alembic commands ###
