"""qa_accounts add token_api_base

Revision ID: 0cf3985261a3
Revises: f6b142f5a88f
Create Date: 2026-06-10 11:05:01.949001
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf3985261a3'
down_revision: Union[str, None] = 'f6b142f5a88f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_accounts', sa.Column('token_api_base', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_accounts', 'token_api_base')
    # ### end Alembic commands ###
