"""qa_cases.parent_id for sub-cases

Revision ID: 00048e91cda0
Revises: a612914a6fcd
Create Date: 2026-06-04 18:16:25.621600
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00048e91cda0'
down_revision: Union[str, None] = 'a612914a6fcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_cases', sa.Column('parent_id', sa.String(length=128), nullable=True))
    op.create_index('idx_parent', 'qa_cases', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_parent', table_name='qa_cases')
    op.drop_column('qa_cases', 'parent_id')
    # ### end Alembic commands ###
