"""qa_runs add resume_at resume_step_index checkpoint

Revision ID: 2c1e7252969a
Revises: fd6a29252f27
Create Date: 2026-06-18 16:51:36.399372
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2c1e7252969a'
down_revision: Union[str, None] = 'fd6a29252f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_runs', sa.Column('resume_at', sa.BigInteger(), nullable=True))
    op.add_column('qa_runs', sa.Column('resume_step_index', sa.Integer(), nullable=True))
    op.add_column('qa_runs', sa.Column('checkpoint', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_runs', 'checkpoint')
    op.drop_column('qa_runs', 'resume_step_index')
    op.drop_column('qa_runs', 'resume_at')
    # ### end Alembic commands ###
