"""qa_markups add tokens_in/out + cost_usd

Revision ID: fd6a29252f27
Revises: 7d51cd168ba1
Create Date: 2026-06-12 17:26:32.064292
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd6a29252f27'
down_revision: Union[str, None] = '7d51cd168ba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_markups', sa.Column('tokens_in', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('qa_markups', sa.Column('tokens_out', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('qa_markups', sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_markups', 'cost_usd')
    op.drop_column('qa_markups', 'tokens_out')
    op.drop_column('qa_markups', 'tokens_in')
    # ### end Alembic commands ###
