"""qa_accounts add display_name/gender

Revision ID: f6b142f5a88f
Revises: b7f3a2c1d4e5
Create Date: 2026-06-10 10:55:55.855635
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6b142f5a88f'
down_revision: Union[str, None] = 'b7f3a2c1d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_accounts', sa.Column('display_name', sa.String(length=64), nullable=True))
    op.add_column('qa_accounts', sa.Column('gender', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_accounts', 'gender')
    op.drop_column('qa_accounts', 'display_name')
    # ### end Alembic commands ###
