"""add qa_markups replies

Revision ID: 3d90dca8bffb
Revises: 5829cd767b9d
Create Date: 2026-06-09 14:58:28.722440
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3d90dca8bffb'
down_revision: Union[str, None] = '5829cd767b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_markups', sa.Column('replies', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_markups', 'replies')
    # ### end Alembic commands ###
