"""qa_markups add kind ip elapsed files commit rollback

Revision ID: 7d51cd168ba1
Revises: 0cf3985261a3
Create Date: 2026-06-10 11:29:37.496743
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7d51cd168ba1'
down_revision: Union[str, None] = '0cf3985261a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_markups', sa.Column('kind', sa.String(length=16), server_default='page', nullable=False))
    op.add_column('qa_markups', sa.Column('ip', sa.String(length=64), nullable=True))
    op.add_column('qa_markups', sa.Column('elapsed_ms', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('qa_markups', sa.Column('files_changed', mysql.JSON(), nullable=True))
    op.add_column('qa_markups', sa.Column('commit_sha', sa.String(length=64), nullable=True))
    op.add_column('qa_markups', sa.Column('rolled_back', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_markups', 'rolled_back')
    op.drop_column('qa_markups', 'commit_sha')
    op.drop_column('qa_markups', 'files_changed')
    op.drop_column('qa_markups', 'elapsed_ms')
    op.drop_column('qa_markups', 'ip')
    op.drop_column('qa_markups', 'kind')
    # ### end Alembic commands ###
